language: python

python:
  - '3.6'

install:
  - pip install pytest pytest-cov python-coveralls

before_script:
  - export PYTHONPATH=.

script:
  - pytest tests

after_success:
  - pytest --cov=chinese tests
  - coverage report
  - coveralls
