language: python

python:
  - '3.6'
  - '3.7'

install:
  - pip install pytest python-coveralls

before_script:
  - export PYTHONPATH=.

script:
  - pytest tests

after_success:
  - coverage run -m pytest tests
  - coverage report
  - coveralls
